### PR TITLE
Adds auto-versioning

### PR DESCRIPTION
**Pull request by 0nary**
**What this PR does / why we need it:**
This PR adds an auto-versioning workflow, he also creates a CI workflow (which will order workflows) and change the behavior of the dotnet behavior to be called by the CI workflow only after the versioning or for PR to not push.
Whit auto-versioning the change of version must only be done in the primary repository.

**Special notes for reviewers:**
A tag is needed (use vX.X.X format).
Add it before merge this pull request, or at least before your next pull on main.

### CODE REVIEW

**Comment by JBBianchi** [comment]
Correct me if I'm wrong but this looks like the `dotnet`pipeline will be triggered both when:
- The CI pipeline is executed (`workflow_call` ?)
- A PR is open, but the `push` job is ignore for pull request.

If so, the PR looks good to me.

**Comment by JBBianchi** [comment]
@0nary : Bonus question, did you try to run the versioning tool with the current framework version (2.0.1.88) to see how it behaves ?

**Comment by 0nary** [comment]
> Correct me if I'm wrong but this looks like the `dotnet`pipeline will be triggered both when:
> 
> * The CI pipeline is executed (`workflow_call` ?)
> * A PR is open, but the `push` job is ignore for pull request.
> 
> If so, the PR looks good to me.

Exactly.

**Comment by 0nary** [comment]
> @0nary : Bonus question, did you try to run the versioning tool with the current framework version (2.0.1.88) to see how it behaves ?

It seems a forgot to dot it, and when I try I have some problems. :/

**Comment by JBBianchi** [comment]
> > @0nary : Bonus question, did you try to run the versioning tool with the current framework version (2.0.1.88) to see how it behaves ?
> 
> It seems a forgot to dot it, and when I try I have some problems. :/

What are the said problems ? What happens if you replace the current version in the csproj files with `2.0.1` ?

**Comment by 0nary** [comment]
```
System.ArgumentException: Invalid version. (Parameter 'version')
   at Semver.SemVersion.Parse(String version, Boolean strict)
```
If I change that work fine.

**Comment by JBBianchi** [comment]
> ```
> System.ArgumentException: Invalid version. (Parameter 'version')
>    at Semver.SemVersion.Parse(String version, Boolean strict)
> ```
> 
> If I change that work fine.

Can you then please add this modification to your PR so it's ready to go when we merge please.

**Review by JBBianchi — APPROVED** [review]

**Pull request merged**
